### ISSUE TITLE
Niezgodność pól pomiędzy szablonem komisji obwodowych, a klasą ObwodowaCsvDto

### ISSUE THREAD

**Issue by pwl89** [OtwartaPlatformaWyborcza/OPW-backend-JavaEE#4]
W szablonie występują następujące kolumny:
`okregowaId[1-51];obwodId;obwodNr;obwodTyp;obwodAddress `

Klasa `ObwodowaCsvDto` posiada pola:
````
String pkwId
String name
String address
String type
int allowedToVote
boolean duplicate
````

CC @adamkowalewski

**Comment by pwl89** [comment]
Obecnie szablon wygląda tak:
```
okregowaId[1-51];obwodId;obwodNr;obwodTyp;obwodAddress 
14;106101-1;1;P;Studio Consulting Sp. z o.o., ul. Romanowska 55F, 91-174 Łódz
```

Obecnie pola klasy wyglądają tak :
```
    private int okregowaPkwId;
    private String pkwId, name, address, type;
    private int allowedToVote;
    private boolean duplicaten
```

okregowaId <-> okregowaPkwId
obwodId  <-> pkwId
obwodNr <-> ??
??  <->  name

**Comment by adamkowalewski** [comment]
* dodane `obwodNr` do entity OpwObwodowa
* rozbicie kolumny `address` na `name` i `address` w szablonie CSV

**Comment by pwl89** [comment]
Trzeba także coś zrobić z `allowedToVote`. - przeoczyłem to rano.

**Comment by pwl89** [comment]
Dodałem pole `obwodNr` do klasy `ObwodowaCsvDto`

**Comment by adamkowalewski** [comment]
Import Komisji Obwodowych z pliku CSV działa. Zamykam issue.
