### ISSUE TITLE
guava NoSuchMethodError ex at user CSV import

### ISSUE THREAD

**Issue by adamkowalewski** [OtwartaPlatformaWyborcza/OPW-backend-JavaEE#7]
Exception: 
`The error message is: java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;`

Related file [UserCsvDtoParser.java](https://github.com/OtwartaPlatformaWyborcza/OPW-backend-JavaEE/blob/master/opw/src/main/java/com/adamkowalewski/opw/view/controller/csv/UserCsvDtoParser.java#l26)

it seems that our CSV user import is affected by external issue 
* https://code.google.com/p/guava-libraries/issues/detail?id=1668
* https://java.net/jira/browse/GLASSFISH-20850

**Comment by pwl89** [comment]
Bug confirmed. Work in progress.
